languageCode = 'zh-cn'
title = '季夏的个人博客'
theme = 'ananke'
baseURL = 'https://jixia8.github.io/'
hasCJKLanguage = true
summaryLength = 140

[params]
  author = "季夏"
  subtitle = "记录学习与生活的点滴"
  description = "个人博客"

[[menu.main]]
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  name = "归档"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 3